spring.application.name=vynder

spring.datasource.url=jdbc:postgresql://localhost:5432/vynder_test1_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
jwt.secret=cowHorse700GoatOmoooVynderSecretKeyPassword99

server.port=${PORT:8080}


#Header authorization bearer token

CLOUDINARY_URL=cloudinary://<your_api_key>:<your_api_secret>@dcyz12ymd

cloudinary.cloud-name= Root
cloudinary.api-key=612233897254699
cloudinary.api-secret=FrF9VjDG1LIDZvZL6WnLt3FfYTM


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB