package com.celpen.vynder.controller;

import com.celpen.vynder.dto.request.InitializePaymentRequest;
import com.celpen.vynder.dto.response.AuthResponse;
import com.celpen.vynder.dto.response.PaymentResponse;
import com.celpen.vynder.model.Application;
import com.celpen.vynder.service.PaymentService;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/payments")
@CrossOrigin("*")
public class PaymentController {

    private final PaymentService paymentService;

    public PaymentController(PaymentService paymentService) {
        this.paymentService = paymentService;
    }

    @PostMapping("/initialize")
    public AuthResponse.PaymentResponse initialize(@RequestBody InitializePaymentRequest request) {
        return paymentService.initializePayment(request);
    }

    @PostMapping("/pay")
    public void payCreator(@RequestParam Long applicationId) {
        // This endpoint would typically be called by a webhook from the payment provider
        // after a successful payment. For simplicity, we're just passing the application ID.
        // In a real implementation, you would verify the payment details before proceeding.
        // You might also want to include security measures to ensure this endpoint is not abused.
        // For example, you could use a secret token that the payment provider includes in the webhook request.
        // Here, we're assuming that the application ID is sufficient for demonstration purposes.
        // In production, you should implement proper validation and security checks.
//        Application app = new Application();
//        app.setId(applicationId);
//        paymentService.payCreator(app);

        System.out.println("hELLO");

    }

    //"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsidmVyaWZ5X2JhbmtfQWNjb3VudF9zZXJ2aWNlIiwicGFzc3BvcnQiLCJhcGktbWFya2V0cGxhY2UiLCJhcGktbWFya2V0cGxhY2Utcm91dGluZyJdLCJzY29wZSI6WyJwcm9maWxlIl0sImV4cCI6MTc3NDM3MTA2MCwibWFya2V0cGxhY2VfdXNlciI6Im11aGFtbWFkaW1tYW1taTdAZ21haWwuY29tIiwiY2xpZW50X25hbWUiOiI1Y2JiZjdiMy0zYjczLTRiY2UtOWJhMS0xNzk2ZTA4ZDcxNzZ8VEVTVCIsImNsaWVudF9sb2dvIjpudWxsLCJqdGkiOiJkOGY3M2E3OS02ODA0LTQwN2UtYWRiMS0xNmU1YzVkMWNjMDYiLCJjbGllbnRfZGVzY3JpcHRpb24iOiIiLCJjbGllbnRfaWQiOiJJS0lBQ0JGMTdBNUI3OEJEN0Q2QUZEOTM1MzRBRUJCQkYxRTRENjQ4MTA3QSIsImFwaS1yb3V0aW5nLWFjdGlvbnMiOlsiVVZCYW5rVmVyaWZpY2F0aW9uIl19.TQjWeXlPBFCF9IwZWNoGV7DgOIsB3CJ2326gmETH8EGPL3hAV5DIQXLB3sz9TGsrOHbnkLIQP7QDfuxgm8c3pbdaV6GCP7fJZgYencAiPOE6e3XRZLQinG19h6AHITXiZWdUjR4jbsSfSXWF78P-y4h-NnwtTrHMrRszDXCB69FbFyYjkPkrwbtrbjZGKoKU558WtGx13mul797rTnlesM8znWjCbdNteZZL2jzGSruguy8htWOimMM3dDvCK6ah0wPijiH58X3gJXKVdxMAo98GOQbAwKuTWoS9FoGpRM7CnQCM5YNYeZ4tbTnHSuKcLvUW7-0bl_WHXf1TdPwbzg

}

//{
//        "success": true,
//        "code": "200",
//        "message": "request processed successfully",
//        "data": [
//        {
//        "id": 879,
//        "name": "78 Finance Company Ltd",
//        "slug": "78-finance-company-ltd-ng",
//        "code": "40195",
//        "longCode": "110072",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 707,
//        "name": "9jaPay Microfinance Bank",
//        "slug": "9japay-microfinance-bank-ng",
//        "code": "090629",
//        "longCode": "090629",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 302,
//        "name": "9mobile 9Payment Service Bank",
//        "slug": "9mobile-9payment-service-bank-ng",
//        "code": "120001",
//        "longCode": "120001",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 174,
//        "name": "Abbey Mortgage Bank",
//        "slug": "abbey-mortgage-bank-ng",
//        "code": "404",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 188,
//        "name": "Above Only MFB",
//        "slug": "above-only-mfb",
//        "code": "51204",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 627,
//        "name": "Abulesoro MFB",
//        "slug": "abulesoro-mfb-ng",
//        "code": "51312",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 1,
//        "name": "Access Bank",
//        "slug": "access-bank",
//        "code": "044",
//        "longCode": "044150149",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 3,
//        "name": "Access Bank (Diamond)",
//        "slug": "access-bank-diamond",
//        "code": "063",
//        "longCode": "063150162",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 495,
//        "name": "Accion Microfinance Bank",
//        "slug": "accion-microfinance-bank-ng",
//        "code": "602",
//        "longCode": "",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 897,
//        "name": "Adamawa Mortgage Bank Limited",
//        "slug": "adamawa-mortgage-bank-limited-ng",
//        "code": "90102",
//        "longCode": "070030",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 687,
//        "name": "Aella MFB",
//        "slug": "aella-mfb-ng",
//        "code": "50315",
//        "longCode": "50315",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 780,
//        "name": "AG Mortgage Bank",
//        "slug": "ag-mortgage-bank-ng",
//        "code": "90077",
//        "longCode": "100028",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 676,
//        "name": "Ahmadu Bello University Microfinance Bank",
//        "slug": "ahmadu-bello-university-microfinance-bank-ng",
//        "code": "50036",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 300,
//        "name": "Airtel Smartcash PSB",
//        "slug": "airtel-smartcash-psb-ng",
//        "code": "120004",
//        "longCode": "120004",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 698,
//        "name": "AKU Microfinance Bank",
//        "slug": "aku-mfb",
//        "code": "51336",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 497,
//        "name": "Akuchukwu Microfinance Bank Limited",
//        "slug": "akuchukwu-microfinance-bank-limited-ng",
//        "code": "090561",
//        "longCode": "090561",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 872,
//        "name": "Al-Barakah Microfinance Bank",
//        "slug": "al-barakah-microfinance-bank-ng",
//        "code": "50055",
//        "longCode": "090133",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 27,
//        "name": "ALAT by WEMA",
//        "slug": "alat-by-wema",
//        "code": "035A",
//        "longCode": "035150103",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 857,
//        "name": "Alpha Morgan Bank",
//        "slug": "alpha-morgan",
//        "code": "108",
//        "longCode": "000041",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 790,
//        "name": "Alternative bank",
//        "slug": "the-alternative-bank-ng",
//        "code": "000304",
//        "longCode": "000304",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 179,
//        "name": "Amju Unique MFB",
//        "slug": "amju-unique-mfb",
//        "code": "50926",
//        "longCode": "511080896",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 614,
//        "name": "Aramoko MFB",
//        "slug": "aramoko-mfb",
//        "code": "50083",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 63,
//        "name": "ASO Savings and Loans",
//        "slug": "asosavings",
//        "code": "401",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 793,
//        "name": "Assets Microfinance Bank",
//        "slug": "assets-microfinance-bank-ng",
//        "code": "50092",
//        "longCode": "50092",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 297,
//        "name": "Astrapolaris MFB LTD",
//        "slug": "astrapolaris-mfb",
//        "code": "MFB50094",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 759,
//        "name": "AVUENEGBE MICROFINANCE BANK",
//        "slug": "avuenegbe-microfinance-bank-ng",
//        "code": "090478",
//        "longCode": "090478",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 778,
//        "name": "AWACASH MICROFINANCE BANK",
//        "slug": "awacash-microfinance-bank-ng",
//        "code": "51351",
//        "longCode": "51351",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 796,
//        "name": "AZTEC MICROFINANCE BANK LIMITED",
//        "slug": "aztec-microfinance-bank-limited-ng",
//        "code": "51337",
//        "longCode": "090540",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 181,
//        "name": "Bainescredit MFB",
//        "slug": "bainescredit-mfb",
//        "code": "51229",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 686,
//        "name": "Banc Corp Microfinance Bank",
//        "slug": "banc-corp-microfinance-bank-ng",
//        "code": "50117",
//        "longCode": "50117",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 880,
//        "name": "Bank78 Microfinance Bank",
//        "slug": "bank78-microfinance-bank-ng",
//        "code": "11072",
//        "longCode": "090866",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 832,
//        "name": "BANKIT MICROFINANCE BANK LTD",
//        "slug": "bankit-microfinance-bank-ltd-ng",
//        "code": "50572",
//        "longCode": "090275",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 689,
//        "name": "BANKLY MFB",
//        "slug": "ampersand-microfinance-bank-ng",
//        "code": "51341",
//        "longCode": "",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 777,
//        "name": "Baobab Microfinance Bank",
//        "slug": "baobab-microfinance-bank-ng",
//        "code": "MFB50992",
//        "longCode": "MFB50992",
//        "gateway": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 783,
//        "name": "BellBank Microfinance Bank",
//        "slug": "bellbank-microfinance-bank-ng",
//        "code": "51100",
//        "longCode": "51100",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 589,
//        "name": "Benysta Microfinance Bank Limited",
//        "slug": "benysta-microfinance-bank-limited",
//        "code": "51267",
//        "longCode": "51267",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 886,
//        "name": "Berachah Microfinance Bank Ltd.",
//        "slug": "berachah-microfinance-bank-ltd-ng",
//        "code": "50122",
//        "longCode": "090618",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 771,
//        "name": "Beststar Microfinance Bank",
//        "slug": "beststar-microfinance-bank-ng",
//        "code": "50123",
//        "longCode": "090615",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 816,
//        "name": "BOLD MFB",
//        "slug": "bold-mfb-ng",
//        "code": "50725",
//        "longCode": "090753",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 815,
//        "name": "Bosak Microfinance Bank",
//        "slug": "bosak-microfinance-bank-ng",
//        "code": "650",
//        "longCode": "650",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 108,
//        "name": "Bowen Microfinance Bank",
//        "slug": "bowen-microfinance-bank",
//        "code": "50931",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 697,
//        "name": "Branch International Finance Company Limited",
//        "slug": "branch",
//        "code": "FC40163",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 867,
//        "name": "Brent Mortgage bank",
//        "slug": "brent-mortgage-bank-ng",
//        "code": "90070",
//        "longCode": "070015",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 817,
//        "name": "BuyPower MFB",
//        "slug": "buypower-mfb-ng",
//        "code": "50645",
//        "longCode": "50645",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 82,
//        "name": "Carbon",
//        "slug": "carbon",
//        "code": "565",
//        "longCode": "",
//        "gateway": "digitalbankmandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 781,
//        "name": "Cashbridge Microfinance Bank Limited",
//        "slug": "cashbridge-mfb-ng",
//        "code": "51353",
//        "longCode": "51353",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 692,
//        "name": "CASHCONNECT MFB",
//        "slug": "cashconnect-mfb-ng",
//        "code": "865",
//        "longCode": "865",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 74,
//        "name": "CEMCS Microfinance Bank",
//        "slug": "cemcs-microfinance-bank",
//        "code": "50823",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 284,
//        "name": "Chanelle Microfinance Bank Limited",
//        "slug": "chanelle-microfinance-bank-limited-ng",
//        "code": "50171",
//        "longCode": "50171",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 704,
//        "name": "Chikum Microfinance bank",
//        "slug": "chikum-microfinance-bank-ng",
//        "code": "312",
//        "longCode": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 2,
//        "name": "Citibank Nigeria",
//        "slug": "citibank-nigeria",
//        "code": "023",
//        "longCode": "023150005",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 755,
//        "name": "CITYCODE MORTAGE BANK",
//        "slug": "citycode-mortage-bank-ng",
//        "code": "070027",
//        "longCode": "070027",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 691,
//        "name": "Consumer Microfinance Bank",
//        "slug": "consumer-microfinance-bank-ng",
//        "code": "50910",
//        "longCode": "50910",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 874,
//        "name": "Cool Microfinance Bank Limited",
//        "slug": "cool-microfinance-bank-limited-ng",
//        "code": "51458",
//        "longCode": "090842",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 895,
//        "name": "Cooperative Mortgage Bank",
//        "slug": "cooperative-mortgage-bank-ng",
//        "code": "90089",
//        "longCode": "070021",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 283,
//        "name": "Corestep MFB",
//        "slug": "corestep-mfb",
//        "code": "50204",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 173,
//        "name": "Coronation Merchant Bank",
//        "slug": "coronation-merchant-bank-ng",
//        "code": "559",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 694,
//        "name": "County Finance Limited",
//        "slug": "county-finance-limited",
//        "code": "FC40128",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 829,
//        "name": "Credit Direct Limited",
//        "slug": "credit-direct-limited-ng",
//        "code": "40119",
//        "longCode": "110049",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 366,
//        "name": "Crescent MFB",
//        "slug": "crescent-mfb",
//        "code": "51297",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 634,
//        "name": "Crust Microfinance Bank",
//        "slug": "crust-microfinance-bank-ng",
//        "code": "090560",
//        "longCode": "",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 820,
//        "name": "CRUTECH MICROFINANCE BANK LTD",
//        "slug": "crutech-microfinance-bank-ltd-ng",
//        "code": "50216",
//        "longCode": "090414",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 865,
//        "name": "Dash Microfinance Bank",
//        "slug": "dash-microfinance-bank-ng",
//        "code": "51368",
//        "longCode": "090845",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 738,
//        "name": "Davenport MICROFINANCE BANK",
//        "slug": "davenport-microfinance-bank-ng",
//        "code": "51334",
//        "longCode": "51334",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 860,
//        "name": "Dillon Microfinance Bank",
//        "slug": "dillon-microfinance-bank-ng",
//        "code": "51450",
//        "longCode": "09828",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 637,
//        "name": "Dot Microfinance Bank",
//        "slug": "dot-microfinance-bank-ng",
//        "code": "50162",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 821,
//        "name": "EBSU Microfinance Bank",
//        "slug": "ebsu-microfinance-bank-ng",
//        "code": "50922",
//        "longCode": "090427",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 4,
//        "name": "Ecobank Nigeria",
//        "slug": "ecobank-nigeria",
//        "code": "050",
//        "longCode": "050150010",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 628,
//        "name": "Ekimogun MFB",
//        "slug": "ekimogun-mfb-ng",
//        "code": "50263",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 64,
//        "name": "Ekondo Microfinance Bank",
//        "slug": "ekondo-microfinance-bank-ng",
//        "code": "098",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 761,
//        "name": "EXCEL FINANCE BANK",
//        "slug": "excel-finance-bank-ng",
//        "code": "090678",
//        "longCode": "090678",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 167,
//        "name": "Eyowo",
//        "slug": "eyowo",
//        "code": "50126",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 677,
//        "name": "Fairmoney Microfinance Bank",
//        "slug": "fairmoney-microfinance-bank-ng",
//        "code": "51318",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 898,
//        "name": "FCMB MFB",
//        "slug": "fcmb-mfb-ng",
//        "code": "51241",
//        "longCode": "51241",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 767,
//        "name": "Fedeth MFB",
//        "slug": "fedeth-mfb-ng",
//        "code": "50298",
//        "longCode": "090482",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 6,
//        "name": "Fidelity Bank",
//        "slug": "fidelity-bank",
//        "code": "070",
//        "longCode": "070150003",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 177,
//        "name": "Firmus MFB",
//        "slug": "firmus-mfb",
//        "code": "51314",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 7,
//        "name": "First Bank of Nigeria",
//        "slug": "first-bank-of-nigeria",
//        "code": "011",
//        "longCode": "011151003",
//        "gateway": "ibank",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 8,
//        "name": "First City Monument Bank",
//        "slug": "first-city-monument-bank",
//        "code": "214",
//        "longCode": "214150018",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 893,
//        "name": "First Option MFB",
//        "slug": "first-option-mfb-ng",
//        "code": "50934",
//        "longCode": "090285",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 757,
//        "name": "FIRST ROYAL MICROFINANCE BANK",
//        "slug": "first-royal-microfinance-bank-ng",
//        "code": "090164",
//        "longCode": "090164",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 812,
//        "name": "FIRSTMIDAS MFB",
//        "slug": "firstmidas-mfb-ng",
//        "code": "51333",
//        "longCode": "090575",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 682,
//        "name": "FirstTrust Mortgage Bank Nigeria",
//        "slug": "firsttrust-mortgage-bank-nigeria-ng",
//        "code": "413",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 882,
//        "name": "Fortress MFB",
//        "slug": "fortress-mfb-ng",
//        "code": "D53",
//        "longCode": "090486",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 112,
//        "name": "FSDH Merchant Bank Limited",
//        "slug": "fsdh-merchant-bank-limited",
//        "code": "501",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 716,
//        "name": "FUTMINNA MICROFINANCE BANK",
//        "slug": "futminna-microfinance-bank-ng",
//        "code": "832",
//        "longCode": "832",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 794,
//        "name": "Garun Mallam MFB",
//        "slug": "garun-mallam-mfb-ng",
//        "code": "MFB51093",
//        "longCode": "MFB51093",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 287,
//        "name": "Gateway Mortgage Bank LTD",
//        "slug": "gateway-mortgage-bank",
//        "code": "812",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 70,
//        "name": "Globus Bank",
//        "slug": "globus-bank",
//        "code": "00103",
//        "longCode": "103015001",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 769,
//        "name": "Goldman MFB",
//        "slug": "goldman-mfb-ng",
//        "code": "090574",
//        "longCode": "950356",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 183,
//        "name": "GoMoney",
//        "slug": "gomoney",
//        "code": "100022",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 756,
//        "name": "GOOD SHEPHERD MICROFINANCE BANK",
//        "slug": "good-shepherd-microfinance-bank-ng",
//        "code": "090664",
//        "longCode": "090664",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 635,
//        "name": "Goodnews Microfinance Bank",
//        "slug": "goodnews-microfinance-bank-ng",
//        "code": "50739",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 633,
//        "name": "Greenwich Merchant Bank",
//        "slug": "greenwich-merchant-bank-ng",
//        "code": "562",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 789,
//        "name": "GROOMING MICROFINANCE BANK",
//        "slug": "grooming-microfinance-bank-ng",
//        "code": "51276",
//        "longCode": "51276",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 824,
//        "name": "GTI MFB",
//        "slug": "gti-mfb-ng",
//        "code": "50368",
//        "longCode": "090385",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 9,
//        "name": "Guaranty Trust Bank",
//        "slug": "guaranty-trust-bank",
//        "code": "058",
//        "longCode": "058152036",
//        "gateway": "ibank",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 111,
//        "name": "Hackman Microfinance Bank",
//        "slug": "hackman-microfinance-bank",
//        "code": "51251",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 81,
//        "name": "Hasal Microfinance Bank",
//        "slug": "hasal-microfinance-bank",
//        "code": "50383",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 877,
//        "name": "Hayat Trust MFB",
//        "slug": "hayat-trust-mfb-ng",
//        "code": "51364",
//        "longCode": "090777",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 301,
//        "name": "HopePSB",
//        "slug": "hopepsb-ng",
//        "code": "120002",
//        "longCode": "120002",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 75,
//        "name": "IBANK Microfinance Bank",
//        "slug": "IBANK-mfb",
//        "code": "51211",
//        "longCode": "090115",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 828,
//        "name": "IBBU MFB",
//        "slug": "ibbu-mfb-ng",
//        "code": "51279",
//        "longCode": "51279",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 168,
//        "name": "Ibile Microfinance Bank",
//        "slug": "ibile-mfb",
//        "code": "51244",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 859,
//        "name": "Ibom Mortgage Bank",
//        "slug": "ibom-mortgage-bank-ng",
//        "code": "90012",
//        "longCode": "070025",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 615,
//        "name": "Ikoyi Osun MFB",
//        "slug": "ikoyi-osun-mfb",
//        "code": "50439",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 636,
//        "name": "Ilaro Poly Microfinance Bank",
//        "slug": "ilaro-poly-microfinance-bank-ng",
//        "code": "50442",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 703,
//        "name": "Imowo MFB",
//        "slug": "imowo-mfb-ng",
//        "code": "50453",
//        "longCode": "50453",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 754,
//        "name": "IMPERIAL HOMES MORTAGE BANK",
//        "slug": "imperial-homes-mortage-bank-ng",
//        "code": "415",
//        "longCode": "100024",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 858,
//        "name": "INDULGE MFB",
//        "slug": "indulge-mfb-ng",
//        "code": "51392",
//        "longCode": "090772",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 892,
//        "name": "INEBA GOGO MFB",
//        "slug": "ineba-gogo-mfb-ng",
//        "code": "51462",
//        "longCode": "090838",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 172,
//        "name": "Infinity MFB",
//        "slug": "infinity-mfb",
//        "code": "50457",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 822,
//        "name": "Infinity trust  Mortgage Bank",
//        "slug": "infinity-trust-mortgage-bank-ng",
//        "code": "070016",
//        "longCode": "070016",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 787,
//        "name": "ISUA MFB",
//        "slug": "isua-mfb-ng",
//        "code": "090701",
//        "longCode": "090701",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 22,
//        "name": "Jaiz Bank",
//        "slug": "jaiz-bank",
//        "code": "301",
//        "longCode": "301080020",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 187,
//        "name": "Kadpoly MFB",
//        "slug": "kadpoly-mfb",
//        "code": "50502",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 768,
//        "name": "KANOPOLY MFB",
//        "slug": "kanopoly-mfb-ng",
//        "code": "51308",
//        "longCode": "090592",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 878,
//        "name": "Kayvee Microfinance Bank",
//        "slug": "kayvee-microfinance-bank-ng",
//        "code": "5129",
//        "longCode": "090554",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 894,
//        "name": "Kebbi Homes Savings and Loans Limited",
//        "slug": "kebbi-homes-savings-and-loans-limited-ng",
//        "code": "90028",
//        "longCode": "070031",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 11,
//        "name": "Keystone Bank",
//        "slug": "keystone-bank",
//        "code": "082",
//        "longCode": "082150017",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 810,
//        "name": "Kolomoni MFB",
//        "slug": "kolomoni-mfb-ng",
//        "code": "899",
//        "longCode": "090480",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 784,
//        "name": "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)",
//        "slug": "kongapay-tech-ltd",
//        "code": "100025",
//        "longCode": "100025",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 184,
//        "name": "Kredi Money MFB LTD",
//        "slug": "kredi-money-mfb",
//        "code": "50200",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 67,
//        "name": "Kuda Bank",
//        "slug": "kuda-bank",
//        "code": "50211",
//        "longCode": "",
//        "gateway": "digitalbankmandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 109,
//        "name": "Lagos Building Investment Company Plc.",
//        "slug": "lbic-plc",
//        "code": "90052",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 523,
//        "name": "Letshego Microfinance Bank",
//        "slug": "letshego-microfinance-bank",
//        "code": "090420",
//        "longCode": "090420",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 180,
//        "name": "Links MFB",
//        "slug": "links-mfb",
//        "code": "50549",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 296,
//        "name": "Living Trust Mortgage Bank",
//        "slug": "living-trust-mortgage-bank",
//        "code": "031",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 753,
//        "name": "LOMA MFB",
//        "slug": "loma-mfb-ng",
//        "code": "50491",
//        "longCode": "090620",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 233,
//        "name": "Lotus Bank",
//        "slug": "lotus-bank",
//        "code": "303",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 873,
//        "name": "Maal MFB",
//        "slug": "maal-mfb-ng",
//        "code": "51444",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 764,
//        "name": "MAINSTREET MICROFINANCE BANK",
//        "slug": "mainstreet-microfinance-bank-ng",
//        "code": "090171",
//        "longCode": "090171",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 175,
//        "name": "Mayfair MFB",
//        "slug": "mayfair-mfb",
//        "code": "50563",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 896,
//        "name": "Mayfresh Mortgage Bank",
//        "slug": "mayfresh-mortgage-bank-ng",
//        "code": "90003",
//        "longCode": "070019",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 887,
//        "name": "Mega Microfinance Bank",
//        "slug": "mega-microfinance-bank-ng",
//        "code": "50570",
//        "longCode": "090824",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 178,
//        "name": "Mint MFB",
//        "slug": "mint-mfb",
//        "code": "50304",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 875,
//        "name": "MINT-FINEX MFB",
//        "slug": "mint-finex-mfb-ng",
//        "code": "09",
//        "longCode": "090281",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 714,
//        "name": "Money Master PSB",
//        "slug": "money-master-psb-ng",
//        "code": "946",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 688,
//        "name": "Moniepoint MFB",
//        "slug": "moniepoint-mfb-ng",
//        "code": "50515",
//        "longCode": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 303,
//        "name": "MTN Momo PSB",
//        "slug": "mtn-momo-psb-ng",
//        "code": "120003",
//        "longCode": "120003",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 739,
//        "name": "MUTUAL BENEFITS MICROFINANCE BANK",
//        "slug": "mutual-benefits-microfinance-bank-ng",
//        "code": "090190",
//        "longCode": "090190",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 758,
//        "name": "NDCC MICROFINANCE BANK",
//        "slug": "ndcc-microfinance-bank-ng",
//        "code": "090679",
//        "longCode": "090679",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 776,
//        "name": "NET MICROFINANCE BANK",
//        "slug": "net-microfinance-bank-ng",
//        "code": "51361",
//        "longCode": "51361",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 774,
//        "name": "Nigerian Navy Microfinance Bank Limited",
//        "slug": "nigerian-navy-microfinance-bank-limited-ng",
//        "code": "51142",
//        "longCode": "090263",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 883,
//        "name": "NIRSAL MICROFINANCE",
//        "slug": "nirsal-microfinance-ng",
//        "code": "51304",
//        "longCode": "090194",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 795,
//        "name": "Nombank MFB",
//        "slug": "nombank-mfb-ng",
//        "code": "50072",
//        "longCode": "090645",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 801,
//        "name": "NOVA BANK",
//        "slug": "nova-bank-ng",
//        "code": "561",
//        "longCode": "060003",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 830,
//        "name": "Novus MFB",
//        "slug": "novus-mfb-ng",
//        "code": "51371",
//        "longCode": "090734",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 715,
//        "name": "NPF MICROFINANCE BANK",
//        "slug": "npf-microfinance-bank-ng",
//        "code": "50629",
//        "longCode": "50629",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 825,
//        "name": "NSUK MICROFINANACE BANK",
//        "slug": "nsuk-microfinanace-bank-ng",
//        "code": "51261",
//        "longCode": "090491",
//        "gateway": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 863,
//        "name": "Olabisi Onabanjo University Microfinance Bank",
//        "slug": "olabisi-onabanjo-university-microfinance-bank-ng",
//        "code": "50689",
//        "longCode": "090272",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 802,
//        "name": "OLUCHUKWU MICROFINANCE BANK LTD",
//        "slug": "oluchukwu-microfinance-bank-ltd-ng",
//        "code": "50697",
//        "longCode": "50697",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 171,
//        "name": "OPay Digital Services Limited (OPay)",
//        "slug": "paycom",
//        "code": "999992",
//        "longCode": "",
//        "gateway": "ibank",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 699,
//        "name": "Optimus Bank Limited",
//        "slug": "optimus-bank-ltd",
//        "code": "107",
//        "longCode": "00107",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 185,
//        "name": "Paga",
//        "slug": "paga",
//        "code": "100002",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 169,
//        "name": "PalmPay",
//        "slug": "palmpay",
//        "code": "999991",
//        "longCode": "",
//        "gateway": "ibank",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 26,
//        "name": "Parallex Bank",
//        "slug": "parallex-bank",
//        "code": "104",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 110,
//        "name": "Parkway - ReadyCash",
//        "slug": "parkway-ready-cash",
//        "code": "311",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 763,
//        "name": "PATHFINDER MICROFINANCE BANK LIMITED",
//        "slug": "pathfinder-microfinance-bank-limited-ng",
//        "code": "090680",
//        "longCode": "090680",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 884,
//        "name": "Paystack MFB",
//        "slug": "paystack-mfb-ng",
//        "code": "51457",
//        "longCode": "090986",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 629,
//        "name": "Paystack-Titan",
//        "slug": "titan-paystack",
//        "code": "100039",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 693,
//        "name": "Peace Microfinance Bank",
//        "slug": "peace-microfinance-bank-ng",
//        "code": "50743",
//        "longCode": "50743",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 775,
//        "name": "PECANTRUST MICROFINANCE BANK LIMITED",
//        "slug": "pecantrust-microfinance-bank-limited-ng",
//        "code": "51226",
//        "longCode": "51226",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 683,
//        "name": "Personal Trust MFB",
//        "slug": "personal-trust-mfb-ng",
//        "code": "51146",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 170,
//        "name": "Petra Mircofinance Bank Plc",
//        "slug": "petra-microfinance-bank-plc",
//        "code": "50746",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 831,
//        "name": "Pettysave MFB",
//        "slug": "pettysave-mfb-ng",
//        "code": "MFB51452",
//        "longCode": "090768",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 762,
//        "name": "PFI FINANCE COMPANY LIMITED",
//        "slug": "pfi-finance-company-limited-ng",
//        "code": "050021",
//        "longCode": "050021",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 705,
//        "name": "Platinum Mortgage Bank",
//        "slug": "platinum-mortgage-bank-ng",
//        "code": "268",
//        "longCode": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 770,
//        "name": "Pocket App",
//        "slug": "pocket",
//        "code": "00716",
//        "longCode": "00716",
//        "gateway": "digitalbankmandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 13,
//        "name": "Polaris Bank",
//        "slug": "polaris-bank",
//        "code": "076",
//        "longCode": "076151006",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 626,
//        "name": "Polyunwana MFB",
//        "slug": "polyunwana-mfb-ng",
//        "code": "50864",
//        "longCode": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 304,
//        "name": "PremiumTrust Bank",
//        "slug": "premiumtrust-bank-ng",
//        "code": "105",
//        "longCode": "000031",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 792,
//        "name": "Prospa Capital Microfinance Bank",
//        "slug": "prospa-capital-microfinance-bank-ng",
//        "code": "50739",
//        "longCode": "50739",
//        "gateway": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 760,
//        "name": "PROSPERIS FINANCE LIMITED",
//        "slug": "prosperis-finance-limited-ng",
//        "code": "050023",
//        "longCode": "050023",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 25,
//        "name": "Providus Bank",
//        "slug": "providus-bank",
//        "code": "101",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 232,
//        "name": "QuickFund MFB",
//        "slug": "quickfund-mfb",
//        "code": "51293",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 176,
//        "name": "Rand Merchant Bank",
//        "slug": "rand-merchant-bank",
//        "code": "502",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 766,
//        "name": "RANDALPHA MICROFINANCE BANK",
//        "slug": "randalpha-microfinance-bank-ng",
//        "code": "090496",
//        "longCode": "090496",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 295,
//        "name": "Refuge Mortgage Bank",
//        "slug": "refuge-mortgage-bank",
//        "code": "90067",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 773,
//        "name": "REHOBOTH MICROFINANCE BANK",
//        "slug": "rehoboth-microfinance-bank-ng",
//        "code": "50761",
//        "longCode": "090463",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 710,
//        "name": "Rephidim Microfinance Bank",
//        "slug": "rephidim",
//        "code": "50994",
//        "longCode": "221151615",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 885,
//        "name": "Retrust Mfb",
//        "slug": "retrust-mfb-ng",
//        "code": "51375",
//        "longCode": "090766",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 700,
//        "name": "Rigo Microfinance Bank Limited",
//        "slug": "rigo-microfinance-bank-limited-ng",
//        "code": "51286",
//        "longCode": "51286",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 679,
//        "name": "ROCKSHIELD MICROFINANCE BANK",
//        "slug": "rockshield-microfinance-bank-ng",
//        "code": "50767",
//        "longCode": "",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 69,
//        "name": "Rubies MFB",
//        "slug": "rubies-mfb",
//        "code": "125",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 286,
//        "name": "Safe Haven MFB",
//        "slug": "safe-haven-mfb-ng",
//        "code": "51113",
//        "longCode": "51113",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 706,
//        "name": "SAGE GREY FINANCE LIMITED",
//        "slug": "sage-grey-finance-limited-ng",
//        "code": "40165",
//        "longCode": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 632,
//        "name": "Shield MFB",
//        "slug": "shield-mfb-ng",
//        "code": "50582",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 750,
//        "name": "Signature Bank Ltd",
//        "slug": "signature-bank-ltd-ng",
//        "code": "106",
//        "longCode": "000034",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 695,
//        "name": "Solid Allianze MFB",
//        "slug": "solid-allianze-mfb",
//        "code": "51062",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 365,
//        "name": "Solid Rock MFB",
//        "slug": "solid-rock-mfb",
//        "code": "50800",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 72,
//        "name": "Sparkle Microfinance Bank",
//        "slug": "sparkle-microfinance-bank",
//        "code": "51310",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 855,
//        "name": "Springfield Microfinance Bank",
//        "slug": "springfield-microfinance-bank-ng",
//        "code": "51429",
//        "longCode": "090806",
//        "gateway": "null",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 14,
//        "name": "Stanbic IBTC Bank",
//        "slug": "stanbic-ibtc-bank",
//        "code": "221",
//        "longCode": "221159522",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 15,
//        "name": "Standard Chartered Bank",
//        "slug": "standard-chartered-bank",
//        "code": "068",
//        "longCode": "068150015",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 765,
//        "name": "STANFORD MICROFINANCE BANK",
//        "slug": "stanford-microfinance-bank-ng",
//        "code": "090162",
//        "longCode": "090162",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 779,
//        "name": "STATESIDE MICROFINANCE BANK",
//        "slug": "stateside-microfinance-bank-ng",
//        "code": "50809",
//        "longCode": "50809",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 826,
//        "name": "STB Mortgage Bank",
//        "slug": "stb-mortgage-bank-ng",
//        "code": "070022",
//        "longCode": "070022",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 285,
//        "name": "Stellas MFB",
//        "slug": "stellas-mfb",
//        "code": "51253",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 16,
//        "name": "Sterling Bank",
//        "slug": "sterling-bank",
//        "code": "232",
//        "longCode": "232150016",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 869,
//        "name": "Summit Bank",
//        "slug": "summit-bank-ng",
//        "code": "00305",
//        "longCode": "080003",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 23,
//        "name": "Suntrust Bank",
//        "slug": "suntrust-bank",
//        "code": "100",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 631,
//        "name": "Supreme MFB",
//        "slug": "supreme-mfb-ng",
//        "code": "50968",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 888,
//        "name": "Sycamore Microfinance Bank",
//        "slug": "sycamore-microfinance-bank-ng",
//        "code": "51056",
//        "longCode": "090827",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 68,
//        "name": "TAJ Bank",
//        "slug": "taj-bank",
//        "code": "302",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 186,
//        "name": "Tangerine Money",
//        "slug": "tangerine-money",
//        "code": "51269",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 889,
//        "name": "Tatum Bank",
//        "slug": "tatum-bank-ng",
//        "code": "109",
//        "longCode": "000042",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 811,
//        "name": "TENN",
//        "slug": "tenn-ng",
//        "code": "51403",
//        "longCode": "090716",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 866,
//        "name": "Think Finance Microfinance Bank",
//        "slug": "think-finance-microfinance-bank-ng",
//        "code": "677",
//        "longCode": "090373",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 73,
//        "name": "Titan Bank",
//        "slug": "titan-bank",
//        "code": "102",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 788,
//        "name": "TransPay MFB",
//        "slug": "transpay-mfb-ng",
//        "code": "090708",
//        "longCode": "090708",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 862,
//        "name": "TRUSTBANC J6 MICROFINANCE BANK",
//        "slug": "trustbanc-j6-microfinance-bank-ng",
//        "code": "51118",
//        "longCode": "090123",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 690,
//        "name": "U&C Microfinance Bank Ltd (U AND C MFB)",
//        "slug": "uc-microfinance-bank-ltd-u-and-c-mfb-ng",
//        "code": "50840",
//        "longCode": "50840",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 786,
//        "name": "UCEE MFB",
//        "slug": "ucee-mfb-ng",
//        "code": "090706",
//        "longCode": "090706",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 630,
//        "name": "Uhuru MFB",
//        "slug": "uhuru-mfb-ng",
//        "code": "51322",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 853,
//        "name": "Ultraviolet Microfinance Bank",
//        "slug": "ultraviolet-microfinance-bank-ng",
//        "code": "51080",
//        "longCode": "090781",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 678,
//        "name": "Unaab Microfinance Bank Limited",
//        "slug": "unaab-microfinance-bank-limited-ng",
//        "code": "50870",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 861,
//        "name": "UNIABUJA MFB",
//        "slug": "uniabuja-mfb",
//        "code": "51447",
//        "longCode": "MFB51447",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 282,
//        "name": "Unical MFB",
//        "slug": "unical-mfb",
//        "code": "50871",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 638,
//        "name": "Unilag Microfinance Bank",
//        "slug": "unilag-microfinance-bank-ng",
//        "code": "51316",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 823,
//        "name": "UNIMAID MICROFINANCE BANK",
//        "slug": "unimaid-microfinance-bank-ng",
//        "code": "50875",
//        "longCode": "090464",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 17,
//        "name": "Union Bank of Nigeria",
//        "slug": "union-bank-of-nigeria",
//        "code": "032",
//        "longCode": "032080474",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 18,
//        "name": "United Bank For Africa",
//        "slug": "united-bank-for-africa",
//        "code": "033",
//        "longCode": "033153513",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 19,
//        "name": "Unity Bank",
//        "slug": "unity-bank",
//        "code": "215",
//        "longCode": "215154097",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 881,
//        "name": "UNIUYO Microfinance Bank Ltd",
//        "slug": "uniuyo-microfinance-bank-ltd-ng",
//        "code": "50880",
//        "longCode": "090315",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 737,
//        "name": "Uzondu Microfinance Bank Awka Anambra State",
//        "slug": "uzondu-microfinance-bank-awka-anambra-state-ng",
//        "code": "50894",
//        "longCode": "50894",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 725,
//        "name": "Vale Finance Limited",
//        "slug": "vale-finance",
//        "code": "050020",
//        "longCode": "",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 71,
//        "name": "VFD Microfinance Bank Limited",
//        "slug": "vfd",
//        "code": "566",
//        "longCode": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 701,
//        "name": "Waya Microfinance Bank",
//        "slug": "waya-microfinance-bank-ng",
//        "code": "51355",
//        "longCode": "51355",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 20,
//        "name": "Wema Bank",
//        "slug": "wema-bank",
//        "code": "035",
//        "longCode": "035150103",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 854,
//        "name": "Weston Charis MFB",
//        "slug": "weston-charis-mfb-ng",
//        "code": "51386",
//        "longCode": "090741",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 827,
//        "name": "Xpress Wallet",
//        "slug": "xpress-wallet-ng",
//        "code": "100040",
//        "longCode": "100040",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 797,
//        "name": "Yes MFB",
//        "slug": "yes-mfb-ng",
//        "code": "594",
//        "longCode": "090142",
//        "gateway": "",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 870,
//        "name": "Zap",
//        "slug": "zap",
//        "code": "00zap",
//        "longCode": "00zap",
//        "gateway": "digitalbankmandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 21,
//        "name": "Zenith Bank",
//        "slug": "zenith-bank",
//        "code": "057",
//        "longCode": "057150013",
//        "gateway": "emandate",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        },
//        {
//        "id": 876,
//        "name": "Zitra MFB",
//        "slug": "zitra-mfb-ng",
//        "code": "51373",
//        "longCode": "090718",
//        "active": true,
//        "country": "Nigeria",
//        "currency": "NGN",
//        "type": "nuban"
//        }
//        ]
//        }
